{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"interrupted"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/SwiftIO\/documentation\/SwiftIO\/Errno","preciseIdentifier":"s:7SwiftIO5ErrnoV","text":"Errno"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["macOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The process caught an asynchronous signal (such as "},{"type":"codeVoice","code":"SIGINT"},{"type":"text","text":" or "},{"type":"codeVoice","code":"SIGQUIT"},{"type":"text","text":")"},{"type":"text","text":" "},{"type":"text","text":"during the execution of an interruptible function."},{"type":"text","text":" "},{"type":"text","text":"If the signal handler performs a normal return,"},{"type":"text","text":" "},{"type":"text","text":"the caller of the interrupted function call receives this error."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The corresponding C error is "},{"type":"codeVoice","code":"EINTR"},{"type":"text","text":"."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/swiftio\/errno\/interrupted"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/SwiftIO\/documentation\/SwiftIO\/Errno\/interrupted","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Interrupted function call."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"interrupted"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Errno","preciseIdentifier":"s:7SwiftIO5ErrnoV"}],"title":"interrupted","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"s:7SwiftIO5ErrnoV11interruptedACvpZ","modules":[{"name":"SwiftIO"}]},"hierarchy":{"paths":[["doc:\/\/SwiftIO\/documentation\/SwiftIO","doc:\/\/SwiftIO\/documentation\/SwiftIO\/Errno"]]},"references":{"doc://SwiftIO/documentation/SwiftIO/Errno/interrupted":{"role":"symbol","title":"interrupted","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"interrupted"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Errno","preciseIdentifier":"s:7SwiftIO5ErrnoV"}],"abstract":[{"type":"text","text":"Interrupted function call."}],"identifier":"doc:\/\/SwiftIO\/documentation\/SwiftIO\/Errno\/interrupted","kind":"symbol","type":"topic","url":"\/documentation\/swiftio\/errno\/interrupted"},"doc://SwiftIO/documentation/SwiftIO":{"role":"collection","title":"SwiftIO","abstract":[{"type":"text","text":"The SwiftIO library allows you to access and control the hardware in an easy way."}],"identifier":"doc:\/\/SwiftIO\/documentation\/SwiftIO","kind":"symbol","type":"topic","url":"\/documentation\/swiftio"},"doc://SwiftIO/documentation/SwiftIO/Errno":{"role":"symbol","title":"Errno","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Errno"}],"abstract":[{"type":"text","text":"The Errno struct lists all the possible errors."}],"identifier":"doc:\/\/SwiftIO\/documentation\/SwiftIO\/Errno","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Errno"}],"url":"\/documentation\/swiftio\/errno"}}}